

// Note: autogenerated
namespace EspnFantasyFootballAnalyzer.Core.EspnData
{
    public class Player
    {
        public int DefaultPositionId { get; set; }
        public List<int> EligibleSlots { get; set; }
        public string FirstName { get; set; }
        public string FullName { get; set; }
        public int Id { get; set; }
        public string LastName { get; set; }
        public int ProTeamId { get; set; }
        public int UniverseId { get; set; }
        public bool Active { get; set; }
        public bool Droppable { get; set; }
        public bool Injured { get; set; }
        public string InjuryStatus { get; set; }
        public object LastNewsDate { get; set; }
        public string SeasonOutlook { get; set; }
        public long? LastVideoDate { get; set; }
    }

    public class PlayerPoolEntry
    {
        public decimal AppliedStatTotal { get; set; }
        public int Id { get; set; }
        public Player Player { get; set; } = new();
        public int KeeperValue { get; set; }
        public int KeeperValueFuture { get; set; }
        public bool LineupLocked { get; set; }
        public int OnTeamId { get; set; }
        public bool RosterLocked { get; set; }
        public string Status { get; set; }
        public bool TradeLocked { get; set; }
    }

    public class Entry
    {
        public int LineupSlotId { get; set; }
        public int PlayerId { get; set; }
        public PlayerPoolEntry PlayerPoolEntry { get; set; }
        public object AcquisitionDate { get; set; }
        public string AcquisitionType { get; set; }
        public string InjuryStatus { get; set; }
        public List<string> PendingTransactionIds { get; set; }
        public string Status { get; set; }
    }

    public class RosterForCurrentScoringPeriod
    {
        public decimal AppliedStatTotal { get; set; }
        public List<Entry> Entries { get; set; }
    }

    public class RosterForMatchupPeriod
    {
        public List<Entry> Entries { get; set; }
    }


    public class RosterForMatchupPeriodDelayed
    {
        public List<object> Entries { get; set; }
    }

    public class Away
    {
        public decimal Adjustment { get; set; }
        public int TeamId { get; set; }
        public decimal Tiebreak { get; set; }
        public decimal TotalPoints { get; set; }
        public RosterForCurrentScoringPeriod RosterForCurrentScoringPeriod { get; set; }
        public RosterForMatchupPeriod RosterForMatchupPeriod { get; set; }
        public RosterForMatchupPeriodDelayed RosterForMatchupPeriodDelayed { get; set; }
        public decimal? TotalPointsLive { get; set; }
        public decimal GamesBack { get; set; }
        public int Losses { get; set; }
        public decimal Percentage { get; set; }
        public decimal PointsAgainst { get; set; }
        public decimal PointsFor { get; set; }
        public int StreakLength { get; set; }
        public string StreakType { get; set; }
        public int Ties { get; set; }
        public int Wins { get; set; }
    }

    public class Home
    {
        public decimal Adjustment { get; set; }
        public int TeamId { get; set; }
        public decimal Tiebreak { get; set; }
        public decimal TotalPoints { get; set; }
        public RosterForCurrentScoringPeriod RosterForCurrentScoringPeriod { get; set; }
        public RosterForMatchupPeriod RosterForMatchupPeriod { get; set; }
        public RosterForMatchupPeriodDelayed RosterForMatchupPeriodDelayed { get; set; }
        public decimal? TotalPointsLive { get; set; }
        public decimal GamesBack { get; set; }
        public int Losses { get; set; }
        public decimal Percentage { get; set; }
        public decimal PointsAgainst { get; set; }
        public decimal PointsFor { get; set; }
        public int StreakLength { get; set; }
        public string StreakType { get; set; }
        public int Ties { get; set; }
        public int Wins { get; set; }
    }

    public class Schedule
    {
        public Away Away { get; set; }
        public Home Home { get; set; }
        public int MatchupPeriodId { get; set; }
        public string Winner { get; set; }
    }

    public class Team
    {
        public string Abbrev { get; set; }
        public int CurrentProjectedRank { get; set; }
        public int DivisionId { get; set; }
        public int DraftDayProjectedRank { get; set; }
        public int Id { get; set; }
        public bool IsActive { get; set; }
        public string Location { get; set; }
        public string Logo { get; set; }
        public string LogoType { get; set; }
        public string Nickname { get; set; }
        public List<string> Owners { get; set; }
        public int PlayoffSeed { get; set; }
        public decimal Points { get; set; }
        public decimal PointsAdjusted { get; set; }
        public decimal PointsDelta { get; set; }
        public string PrimaryOwner { get; set; }
        public int RankCalculatedFinal { get; set; }
        public int RankFinal { get; set; }
        public int WaiverRank { get; set; }
        public List<int> WatchList { get; set; }
    }

    public class Root
    {
        public int GameId { get; set; }
        public int Id { get; set; }
        public List<Schedule> Schedule { get; set; }
        public int ScoringPeriodId { get; set; }
        public int SeasonId { get; set; }
        public int SegmentId { get; set; }
        public List<Team> Teams { get; set; }
    }
}