using System.Collections.Generic;

// Note: autogenerated
namespace EspnFantasyFootballAnalyzer.Core.EspnData
{
    public class DraftDetail
    {
        public long CompleteDate { get; set; }
        public bool Drafted { get; set; }
        public bool InProgress { get; set; }
    }

    public class NotificationSetting
    {
        public bool Enabled { get; set; }
        public string Id { get; set; }
        public string Type { get; set; }
    }

    public class Member
    {
        public string DisplayName { get; set; }
        public string FirstName { get; set; }
        public string Id { get; set; }
        public bool IsLeagueCreator { get; set; }
        public bool IsLeagueManager { get; set; }
        public string LastName { get; set; }
        public List<NotificationSetting> NotificationSettings { get; set; }
    }

    public class _128
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _129
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _130
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _3
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
        public int AuctionValue { get; set; }
        public bool Published { get; set; }
        public int RankSourceId { get; set; }
        public string RankType { get; set; }
        public int SlotId { get; set; }
        public decimal? AverageRank { get; set; }
    }

    public class _4
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _132
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _133
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _134
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _198
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _135
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _72
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _136
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _201
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _77
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _80
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _19
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _20
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _85
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _86
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _24
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _25
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _89
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _26
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _90
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _91
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _92
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _93
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _95
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _96
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _97
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _98
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _99
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _101
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _102
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _103
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _104
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _42
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _43
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _44
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _53
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _123
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _124
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _125
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class _63
    {
        public bool Ineligible { get; set; }
        public decimal Rank { get; set; }
        public object Result { get; set; }
        public decimal Score { get; set; }
    }

    public class ScoreByStat
    {
        public _128 _128 { get; set; }
        public _129 _129 { get; set; }
        public _130 _130 { get; set; }
        public _3 _3 { get; set; }
        public _4 _4 { get; set; }
        public _132 _132 { get; set; }
        public _133 _133 { get; set; }
        public _134 _134 { get; set; }
        public _198 _198 { get; set; }
        public _135 _135 { get; set; }
        public _72 _72 { get; set; }
        public _136 _136 { get; set; }
        public _201 _201 { get; set; }
        public _77 _77 { get; set; }
        public _80 _80 { get; set; }
        public _19 _19 { get; set; }
        public _20 _20 { get; set; }
        public _85 _85 { get; set; }
        public _86 _86 { get; set; }
        public _24 _24 { get; set; }
        public _25 _25 { get; set; }
        public _89 _89 { get; set; }
        public _26 _26 { get; set; }
        public _90 _90 { get; set; }
        public _91 _91 { get; set; }
        public _92 _92 { get; set; }
        public _93 _93 { get; set; }
        public _95 _95 { get; set; }
        public _96 _96 { get; set; }
        public _97 _97 { get; set; }
        public _98 _98 { get; set; }
        public _99 _99 { get; set; }
        public _101 _101 { get; set; }
        public _102 _102 { get; set; }
        public _103 _103 { get; set; }
        public _104 _104 { get; set; }
        public _42 _42 { get; set; }
        public _43 _43 { get; set; }
        public _44 _44 { get; set; }
        public _53 _53 { get; set; }
        public _123 _123 { get; set; }
        public _124 _124 { get; set; }
        public _125 _125 { get; set; }
        public _63 _63 { get; set; }
    }

    public class CumulativeScore
    {
        public int Losses { get; set; }
        public ScoreByStat ScoreByStat { get; set; }
        public object StatBySlot { get; set; }
        public int Ties { get; set; }
        public int Wins { get; set; }
    }

    public class PointsByScoringPeriod
    {
        public decimal _1 { get; set; }
        public decimal? _2 { get; set; }
    }

    public class AppliedStats
    {
        public decimal _53 { get; set; }
        public decimal _72 { get; set; }
        public decimal _24 { get; set; }
        public decimal _25 { get; set; }
        public decimal _26 { get; set; }
        public decimal _42 { get; set; }
        public decimal _43 { get; set; }
        public decimal _44 { get; set; }
        public decimal _63 { get; set; }
        public decimal? _19 { get; set; }
        public decimal? _3 { get; set; }
        public decimal? _4 { get; set; }
        public decimal? _20 { get; set; }
        public decimal? _96 { get; set; }
        public decimal? _97 { get; set; }
        public decimal? _129 { get; set; }
        public decimal? _98 { get; set; }
        public decimal? _130 { get; set; }
        public decimal? _99 { get; set; }
        public decimal? _132 { get; set; }
        public decimal? _133 { get; set; }
        public decimal? _101 { get; set; }
        public decimal? _134 { get; set; }
        public decimal? _102 { get; set; }
        public decimal? _135 { get; set; }
        public decimal? _103 { get; set; }
        public decimal? _136 { get; set; }
        public decimal? _104 { get; set; }
        public decimal? _89 { get; set; }
        public decimal? _90 { get; set; }
        public decimal? _123 { get; set; }
        public decimal? _91 { get; set; }
        public decimal? _92 { get; set; }
        public decimal? _124 { get; set; }
        public decimal? _93 { get; set; }
        public decimal? _125 { get; set; }
        public decimal? _95 { get; set; }
        public decimal? _128 { get; set; }
    }
    
    public class Player
    {
        public int DefaultPositionId { get; set; }
        public List<int> EligibleSlots { get; set; }
        public string FirstName { get; set; }
        public string FullName { get; set; }
        public int Id { get; set; }
        public string LastName { get; set; }
        public int ProTeamId { get; set; }
        public int UniverseId { get; set; }
        public bool Active { get; set; }
        public DraftRanksByRankType DraftRanksByRankType { get; set; }
        public bool Droppable { get; set; }
        public bool Injured { get; set; }
        public string InjuryStatus { get; set; }
        public object LastNewsDate { get; set; }
        public Outlooks Outlooks { get; set; }
        public Ownership Ownership { get; set; }
        public string SeasonOutlook { get; set; }
        public long? LastVideoDate { get; set; }
    }

    public class PlayerPoolEntry
    {
        public decimal AppliedStatTotal { get; set; }
        public int Id { get; set; }
        public Player Player { get; set; } = new();
        public int KeeperValue { get; set; }
        public int KeeperValueFuture { get; set; }
        public bool LineupLocked { get; set; }
        public int OnTeamId { get; set; }
        public bool RosterLocked { get; set; }
        public string Status { get; set; }
        public bool TradeLocked { get; set; }
    }

    public class Entry
    {
        public int LineupSlotId { get; set; }
        public int PlayerId { get; set; }
        public PlayerPoolEntry PlayerPoolEntry { get; set; }
        public object AcquisitionDate { get; set; }
        public string AcquisitionType { get; set; }
        public string InjuryStatus { get; set; }
        public List<string> PendingTransactionIds { get; set; }
        public string Status { get; set; }
    }

    public class RosterForCurrentScoringPeriod
    {
        public decimal AppliedStatTotal { get; set; }
        public List<Entry> Entries { get; set; }
    }

    public class RosterForMatchupPeriod
    {
        public List<Entry> Entries { get; set; }
    }
    

    public class RosterForMatchupPeriodDelayed
    {
        public List<object> Entries { get; set; }
    }

    public class Away
    {
        public decimal Adjustment { get; set; }
        public CumulativeScore CumulativeScore { get; set; }
        public PointsByScoringPeriod PointsByScoringPeriod { get; set; }
        public int TeamId { get; set; }
        public decimal Tiebreak { get; set; }
        public decimal TotalPoints { get; set; }
        public RosterForCurrentScoringPeriod RosterForCurrentScoringPeriod { get; set; }
        public RosterForMatchupPeriod RosterForMatchupPeriod { get; set; }
        public RosterForMatchupPeriodDelayed RosterForMatchupPeriodDelayed { get; set; }
        public decimal? TotalPointsLive { get; set; }
        public decimal GamesBack { get; set; }
        public int Losses { get; set; }
        public decimal Percentage { get; set; }
        public decimal PointsAgainst { get; set; }
        public decimal PointsFor { get; set; }
        public int StreakLength { get; set; }
        public string StreakType { get; set; }
        public int Ties { get; set; }
        public int Wins { get; set; }
    }

    public class Home
    {
        public decimal Adjustment { get; set; }
        public CumulativeScore CumulativeScore { get; set; }
        public PointsByScoringPeriod PointsByScoringPeriod { get; set; }
        public int TeamId { get; set; }
        public decimal Tiebreak { get; set; }
        public decimal TotalPoints { get; set; }
        public RosterForCurrentScoringPeriod RosterForCurrentScoringPeriod { get; set; }
        public RosterForMatchupPeriod RosterForMatchupPeriod { get; set; }
        public RosterForMatchupPeriodDelayed RosterForMatchupPeriodDelayed { get; set; }
        public decimal? TotalPointsLive { get; set; }
        public decimal GamesBack { get; set; }
        public int Losses { get; set; }
        public decimal Percentage { get; set; }
        public decimal PointsAgainst { get; set; }
        public decimal PointsFor { get; set; }
        public int StreakLength { get; set; }
        public string StreakType { get; set; }
        public int Ties { get; set; }
        public int Wins { get; set; }
    }

    public class Schedule
    {
        public Away Away { get; set; }
        public Home Home { get; set; }
        public int Id { get; set; }
        public int MatchupPeriodId { get; set; }
        public string PlayoffTierType { get; set; }
        public string Winner { get; set; }
    }

    public class AcquisitionSettings
    {
        public int AcquisitionBudget { get; set; }
        public int AcquisitionLimit { get; set; }
        public string AcquisitionType { get; set; }
        public bool IsUsingAcquisitionBudget { get; set; }
        public decimal MatchupAcquisitionLimit { get; set; }
        public bool MatchupLimitPerScoringPeriod { get; set; }
        public int MinimumBid { get; set; }
        public int WaiverHours { get; set; }
        public bool WaiverOrderReset { get; set; }
        public List<string> WaiverProcessDays { get; set; }
        public int WaiverProcessHour { get; set; }
    }

    public class DraftSettings
    {
        public int AuctionBudget { get; set; }
        public long AvailableDate { get; set; }
        public long Date { get; set; }
        public bool IsTradingEnabled { get; set; }
        public int KeeperCount { get; set; }
        public int KeeperCountFuture { get; set; }
        public string KeeperOrderType { get; set; }
        public string LeagueSubType { get; set; }
        public string OrderType { get; set; }
        public List<int> PickOrder { get; set; }
        public int TimePerSelection { get; set; }
        public string Type { get; set; }
    }

    public class FinanceSettings
    {
        public decimal EntryFee { get; set; }
        public decimal MiscFee { get; set; }
        public decimal PerLoss { get; set; }
        public decimal PerTrade { get; set; }
        public decimal PlayerAcquisition { get; set; }
        public decimal PlayerDrop { get; set; }
        public decimal PlayerMoveToActive { get; set; }
        public decimal PlayerMoveToIR { get; set; }
    }

    public class LineupSlotCounts
    {
        public int _0 { get; set; }
        public int _1 { get; set; }
        public int _2 { get; set; }
        public int _3 { get; set; }
        public int _4 { get; set; }
        public int _5 { get; set; }
        public int _6 { get; set; }
        public int _7 { get; set; }
        public int _8 { get; set; }
        public int _9 { get; set; }
        public int _10 { get; set; }
        public int _11 { get; set; }
        public int _12 { get; set; }
        public int _13 { get; set; }
        public int _14 { get; set; }
        public int _15 { get; set; }
        public int _16 { get; set; }
        public int _17 { get; set; }
        public int _18 { get; set; }
        public int _19 { get; set; }
        public int _20 { get; set; }
        public int _21 { get; set; }
        public int _22 { get; set; }
        public int _23 { get; set; }
        public int _24 { get; set; }
    }

    public class LineupSlotStatLimits
    {
    }

    public class PositionLimits
    {
        public int _0 { get; set; }
        public int _1 { get; set; }
        public int _2 { get; set; }
        public int _3 { get; set; }
        public int _4 { get; set; }
        public int _5 { get; set; }
        public int _6 { get; set; }
        public int _7 { get; set; }
        public int _8 { get; set; }
        public int _9 { get; set; }
        public int _10 { get; set; }
        public int _11 { get; set; }
        public int _12 { get; set; }
        public int _13 { get; set; }
        public int _14 { get; set; }
        public int _15 { get; set; }
        public int _16 { get; set; }
        public int _17 { get; set; }
    }

    public class RosterSettings
    {
        public bool IsBenchUnlimited { get; set; }
        public bool IsUsingUndroppableList { get; set; }
        public string LineupLocktimeType { get; set; }
        public LineupSlotCounts LineupSlotCounts { get; set; }
        public LineupSlotStatLimits LineupSlotStatLimits { get; set; }
        public int MoveLimit { get; set; }
        public PositionLimits PositionLimits { get; set; }
        public string RosterLocktimeType { get; set; }
        public List<int> UniverseIds { get; set; }
    }

    public class Division
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Size { get; set; }
    }

    public class MatchupPeriods
    {
        public List<int> _1 { get; set; }
        public List<int> _2 { get; set; }
        public List<int> _3 { get; set; }
        public List<int> _4 { get; set; }
        public List<int> _5 { get; set; }
        public List<int> _6 { get; set; }
        public List<int> _7 { get; set; }
        public List<int> _8 { get; set; }
        public List<int> _9 { get; set; }
        public List<int> _10 { get; set; }
        public List<int> _11 { get; set; }
        public List<int> _12 { get; set; }
        public List<int> _13 { get; set; }
        public List<int> _14 { get; set; }
        public List<int> _15 { get; set; }
        public List<int> _16 { get; set; }
    }

    public class ScheduleSettings
    {
        public List<Division> Divisions { get; set; }
        public int MatchupPeriodCount { get; set; }
        public int MatchupPeriodLength { get; set; }
        public MatchupPeriods MatchupPeriods { get; set; }
        public int PeriodTypeId { get; set; }
        public int PlayoffMatchupPeriodLength { get; set; }
        public string PlayoffSeedingRule { get; set; }
        public int PlayoffSeedingRuleBy { get; set; }
        public int PlayoffTeamCount { get; set; }
    }

    public class PointsOverrides
    {
        public decimal _16 { get; set; }
    }

    public class ScoringItem
    {
        public bool IsReverseItem { get; set; }
        public decimal LeagueRanking { get; set; }
        public decimal LeagueTotal { get; set; }
        public decimal Points { get; set; }
        public PointsOverrides PointsOverrides { get; set; }
        public int StatId { get; set; }
    }

    public class ScoringSettings
    {
        public bool AllowOutOfPositionScoring { get; set; }
        public int HomeTeamBonus { get; set; }
        public string MatchupTieRule { get; set; }
        public int MatchupTieRuleBy { get; set; }
        public string PlayerRankType { get; set; }
        public int PlayoffHomeTeamBonus { get; set; }
        public string PlayoffMatchupTieRule { get; set; }
        public int PlayoffMatchupTieRuleBy { get; set; }
        public List<ScoringItem> ScoringItems { get; set; }
        public string ScoringType { get; set; }
    }

    public class TradeSettings
    {
        public bool AllowOutOfUniverse { get; set; }
        public long DeadlineDate { get; set; }
        public int Max { get; set; }
        public int RevisionHours { get; set; }
        public int VetoVotesRequired { get; set; }
    }

    public class Settings
    {
        public AcquisitionSettings AcquisitionSettings { get; set; }
        public DraftSettings DraftSettings { get; set; }
        public FinanceSettings FinanceSettings { get; set; }
        public bool IsCustomizable { get; set; }
        public bool IsPublic { get; set; }
        public string Name { get; set; }
        public string RestrictionType { get; set; }
        public RosterSettings RosterSettings { get; set; }
        public ScheduleSettings ScheduleSettings { get; set; }
        public ScoringSettings ScoringSettings { get; set; }
        public int Size { get; set; }
        public TradeSettings TradeSettings { get; set; }
    }

    public class LastUpdateInfo
    {
        public object ClientAddress { get; set; }
        public string Platform { get; set; }
        public string Source { get; set; }
    }
    
    public class Status
    {
        public long ActivatedDate { get; set; }
        public int CreatedAsLeagueType { get; set; }
        public int CurrentLeagueType { get; set; }
        public int CurrentMatchupPeriod { get; set; }
        public int FinalScoringPeriod { get; set; }
        public int FirstScoringPeriod { get; set; }
        public bool IsActive { get; set; }
        public bool IsExpired { get; set; }
        public bool IsFull { get; set; }
        public bool IsPlayoffMatchupEdited { get; set; }
        public bool IsToBeDeleted { get; set; }
        public bool IsViewable { get; set; }
        public bool IsWaiverOrderEdited { get; set; }
        public LastUpdateInfo LastUpdateInfo { get; set; }
        public int LatestScoringPeriod { get; set; }
        public List<int> PreviousSeasons { get; set; }
        public long StandingsUpdateDate { get; set; }
        public int TeamsJoined { get; set; }
        public int TransactionScoringPeriod { get; set; }
        public long WaiverLastExecutionDate { get; set; }
    }

    public class DraftStrategy
    {
        public List<object> FutureKeeperPlayerIds { get; set; }
        public List<object> KeeperPlayerIds { get; set; }
    }

    public class Item
    {
        public int FromLineupSlotId { get; set; }
        public int FromTeamId { get; set; }
        public bool IsKeeper { get; set; }
        public int OverallPickNumber { get; set; }
        public int PlayerId { get; set; }
        public int ToLineupSlotId { get; set; }
        public int ToTeamId { get; set; }
        public string Type { get; set; }
    }

    public class PendingTransaction
    {
        public int BidAmount { get; set; }
        public string ExecutionType { get; set; }
        public string Id { get; set; }
        public bool IsActingAsTeamOwner { get; set; }
        public bool IsLeagueManager { get; set; }
        public bool IsPending { get; set; }
        public List<Item> Items { get; set; }
        public string MemberId { get; set; }
        public object ProcessDate { get; set; }
        public object ProposedDate { get; set; }
        public int Rating { get; set; }
        public int ScoringPeriodId { get; set; }
        public bool SkipTransactionCounters { get; set; }
        public string Status { get; set; }
        public int SubOrder { get; set; }
        public int TeamId { get; set; }
        public string Type { get; set; }
    }

    public class Division2
    {
        public decimal GamesBack { get; set; }
        public int Losses { get; set; }
        public decimal Percentage { get; set; }
        public decimal PointsAgainst { get; set; }
        public decimal PointsFor { get; set; }
        public int StreakLength { get; set; }
        public string StreakType { get; set; }
        public int Ties { get; set; }
        public int Wins { get; set; }
    }

    public class Overall
    {
        public decimal GamesBack { get; set; }
        public int Losses { get; set; }
        public decimal Percentage { get; set; }
        public decimal PointsAgainst { get; set; }
        public decimal PointsFor { get; set; }
        public int StreakLength { get; set; }
        public string StreakType { get; set; }
        public int Ties { get; set; }
        public int Wins { get; set; }
    }

    public class Record
    {
        public Away Away { get; set; }
        public Division Division { get; set; }
        public Home Home { get; set; }
        public Overall Overall { get; set; }
    }

    public class STANDARD
    {
        public int AuctionValue { get; set; }
        public bool Published { get; set; }
        public int Rank { get; set; }
        public int RankSourceId { get; set; }
        public string RankType { get; set; }
        public int SlotId { get; set; }
    }

    public class PPR
    {
        public int AuctionValue { get; set; }
        public bool Published { get; set; }
        public int Rank { get; set; }
        public int RankSourceId { get; set; }
        public string RankType { get; set; }
        public int SlotId { get; set; }
    }

    public class DraftRanksByRankType
    {
        public STANDARD STANDARD { get; set; }
        public PPR PPR { get; set; }
    }

    public class OutlooksByWeek
    {
        public string _1 { get; set; }
        public string _2 { get; set; }
        public string _3 { get; set; }
    }

    public class Outlooks
    {
        public OutlooksByWeek OutlooksByWeek { get; set; }
    }

    public class Ownership
    {
        public decimal AuctionValueAverage { get; set; }
        public decimal AverageDraftPosition { get; set; }
        public decimal PercentChange { get; set; }
        public decimal PercentOwned { get; set; }
        public decimal PercentStarted { get; set; }
    }

    public class Roster
    {
        public decimal AppliedStatTotal { get; set; }
        public List<Entry> Entries { get; set; }
        public int TradeReservedEntries { get; set; }
    }

    public class TradeBlock
    {
    }

    public class MatchupAcquisitionTotals
    {
        public int _2 { get; set; }
        public int? _1 { get; set; }
    }

    public class TransactionCounter
    {
        public int AcquisitionBudgetSpent { get; set; }
        public int Acquisitions { get; set; }
        public int Drops { get; set; }
        public MatchupAcquisitionTotals MatchupAcquisitionTotals { get; set; }
        public int Misc { get; set; }
        public int MoveToActive { get; set; }
        public int MoveToIR { get; set; }
        public decimal Paid { get; set; }
        public decimal TeamCharges { get; set; }
        public int Trades { get; set; }
    }

    public class ValuesByStat
    {
        public decimal _128 { get; set; }
        public decimal _129 { get; set; }
        public decimal _130 { get; set; }
        public decimal _3 { get; set; }
        public decimal _4 { get; set; }
        public decimal _132 { get; set; }
        public decimal _133 { get; set; }
        public decimal _134 { get; set; }
        public decimal _198 { get; set; }
        public decimal _135 { get; set; }
        public decimal _72 { get; set; }
        public decimal _136 { get; set; }
        public decimal _201 { get; set; }
        public decimal _77 { get; set; }
        public decimal _80 { get; set; }
        public decimal _19 { get; set; }
        public decimal _20 { get; set; }
        public decimal _85 { get; set; }
        public decimal _86 { get; set; }
        public decimal _24 { get; set; }
        public decimal _25 { get; set; }
        public decimal _89 { get; set; }
        public decimal _26 { get; set; }
        public decimal _90 { get; set; }
        public decimal _91 { get; set; }
        public decimal _92 { get; set; }
        public decimal _93 { get; set; }
        public decimal _95 { get; set; }
        public decimal _96 { get; set; }
        public decimal _97 { get; set; }
        public decimal _98 { get; set; }
        public decimal _99 { get; set; }
        public decimal _101 { get; set; }
        public decimal _102 { get; set; }
        public decimal _103 { get; set; }
        public decimal _104 { get; set; }
        public decimal _42 { get; set; }
        public decimal _43 { get; set; }
        public decimal _44 { get; set; }
        public decimal _53 { get; set; }
        public decimal _123 { get; set; }
        public decimal _124 { get; set; }
        public decimal _125 { get; set; }
        public decimal _63 { get; set; }
    }

    public class Team
    {
        public string Abbrev { get; set; }
        public int CurrentProjectedRank { get; set; }
        public int DivisionId { get; set; }
        public int DraftDayProjectedRank { get; set; }
        public DraftStrategy DraftStrategy { get; set; }
        public int Id { get; set; }
        public bool IsActive { get; set; }
        public string Location { get; set; }
        public string Logo { get; set; }
        public string LogoType { get; set; }
        public string Nickname { get; set; }
        public List<string> Owners { get; set; }
        public List<PendingTransaction> PendingTransactions { get; set; }
        public int PlayoffSeed { get; set; }
        public decimal Points { get; set; }
        public decimal PointsAdjusted { get; set; }
        public decimal PointsDelta { get; set; }
        public string PrimaryOwner { get; set; }
        public int RankCalculatedFinal { get; set; }
        public int RankFinal { get; set; }
        public Record Record { get; set; }
        public Roster Roster { get; set; }
        public TradeBlock TradeBlock { get; set; }
        public TransactionCounter TransactionCounter { get; set; }
        public ValuesByStat ValuesByStat { get; set; }
        public int WaiverRank { get; set; }
        public List<int> WatchList { get; set; }
    }

    public class Root
    {
        public DraftDetail DraftDetail { get; set; }
        public int GameId { get; set; }
        public int Id { get; set; }
        public List<Member> Members { get; set; }
        public List<Schedule> Schedule { get; set; }
        public int ScoringPeriodId { get; set; }
        public int SeasonId { get; set; }
        public int SegmentId { get; set; }
        public Settings Settings { get; set; }
        public Status Status { get; set; }
        public List<Team> Teams { get; set; }
    }
}